sudo: required
services:
  - docker

before_install:
  - docker build -t luciferro1904/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true luciferro1904/docker-react-practice npm run test