version: '3'
services:
  front:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/front/node_modules
      - ./front:/app/front
  front-tests:
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - /app/front/node_modules
        - ./front:/app/front
      command: ["npm", "run", "test"]